"""PDF export builder — cover pages, TOC, Bates numbering, exhibit bundles."""
from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Optional

from fpdf import FPDF

from casepulse.storage.database import Database


class CasePulsePDF(FPDF):
    """Custom PDF with CasePulse headers and footers."""

    def __init__(self, case_name: str = "", case_number: str = "",
                 exhibit_prefix: str = "", bates_start: int = 1):
        super().__init__()
        self.case_name = case_name
        self.case_number = case_number
        self.exhibit_prefix = exhibit_prefix
        self._bates_counter = bates_start
        self._current_exhibit = ""
        self.set_auto_page_break(auto=True, margin=25)

    def header(self):
        if self.page_no() == 1 and not self._current_exhibit:
            return  # Skip header on cover page
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(100, 100, 100)
        if self._current_exhibit:
            self.cell(0, 5, self._current_exhibit, align="L")
        if self.case_number:
            self.cell(0, 5, f"File: {self.case_number}", align="R", new_x="LMARGIN", new_y="NEXT")
        else:
            self.ln(5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)

    def footer(self):
        self.set_y(-20)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(100, 100, 100)
        # Bates number on left
        if self._current_exhibit:
            bates = f"{self.exhibit_prefix}_{self._bates_counter:05d}" if self.exhibit_prefix else f"BATES_{self._bates_counter:05d}"
            self.cell(0, 5, bates, align="L")
            self._bates_counter += 1
        # Page number on right
        self.cell(0, 5, f"Page {self.page_no()}", align="R")

    def add_cover_page(self, title: str, subtitle: str = "",
                       prepared_by: str = "", date_range: str = ""):
        """Add a formal cover page."""
        self.add_page()
        self.ln(60)
        self.set_font("Helvetica", "B", 24)
        self.set_text_color(0, 0, 0)
        self.cell(0, 15, title, align="C", new_x="LMARGIN", new_y="NEXT")

        if subtitle:
            self.set_font("Helvetica", "", 14)
            self.set_text_color(80, 80, 80)
            self.ln(5)
            self.cell(0, 10, subtitle, align="C", new_x="LMARGIN", new_y="NEXT")

        self.ln(20)
        self.set_font("Helvetica", "", 11)
        self.set_text_color(0, 0, 0)

        if self.case_name:
            self.cell(0, 8, f"Case: {self.case_name}", align="C", new_x="LMARGIN", new_y="NEXT")
        if self.case_number:
            self.cell(0, 8, f"Court File: {self.case_number}", align="C", new_x="LMARGIN", new_y="NEXT")
        if date_range:
            self.cell(0, 8, f"Date Range: {date_range}", align="C", new_x="LMARGIN", new_y="NEXT")
        if prepared_by:
            self.ln(10)
            self.cell(0, 8, f"Prepared by: {prepared_by}", align="C", new_x="LMARGIN", new_y="NEXT")

        self.ln(10)
        self.set_font("Helvetica", "I", 9)
        self.set_text_color(120, 120, 120)
        self.cell(0, 8, f"Generated: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}",
                  align="C", new_x="LMARGIN", new_y="NEXT")
        self.cell(0, 8, "Generated by CasePulse", align="C", new_x="LMARGIN", new_y="NEXT")

    def add_toc(self, items: list[dict]):
        """Add a table of contents page.

        items: [{exhibit_label, date, sender, subject, page}]
        """
        self.add_page()
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(0, 0, 0)
        self.cell(0, 12, "Table of Contents", new_x="LMARGIN", new_y="NEXT")
        self.ln(5)

        self.set_font("Helvetica", "B", 8)
        self.set_fill_color(230, 230, 230)
        self.cell(25, 7, "Exhibit", border=1, fill=True)
        self.cell(22, 7, "Date", border=1, fill=True)
        self.cell(45, 7, "From", border=1, fill=True)
        self.cell(80, 7, "Subject", border=1, fill=True)
        self.cell(18, 7, "Page", border=1, fill=True, new_x="LMARGIN", new_y="NEXT")

        self.set_font("Helvetica", "", 7)
        for item in items:
            if self.get_y() > 265:
                self.add_page()
                self.set_font("Helvetica", "B", 8)
                self.set_fill_color(230, 230, 230)
                self.cell(25, 7, "Exhibit", border=1, fill=True)
                self.cell(22, 7, "Date", border=1, fill=True)
                self.cell(45, 7, "From", border=1, fill=True)
                self.cell(80, 7, "Subject", border=1, fill=True)
                self.cell(18, 7, "Page", border=1, fill=True, new_x="LMARGIN", new_y="NEXT")
                self.set_font("Helvetica", "", 7)

            exhibit = str(item.get("exhibit_label", ""))[:12]
            dt = str(item.get("date", ""))[:10]
            sender = _safe(item.get("sender", ""))[:25]
            subject = _safe(item.get("subject", ""))[:45]
            page = str(item.get("page", ""))

            self.cell(25, 6, exhibit, border=1)
            self.cell(22, 6, dt, border=1)
            self.cell(45, 6, sender, border=1)
            self.cell(80, 6, subject, border=1)
            self.cell(18, 6, page, border=1, new_x="LMARGIN", new_y="NEXT")

    def add_email_exhibit(self, email: dict, exhibit_label: str,
                          attachments: list[dict] = None):
        """Add an email as a numbered exhibit."""
        self._current_exhibit = exhibit_label
        self.add_page()

        # Exhibit header
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(0, 0, 0)
        self.cell(0, 10, exhibit_label, new_x="LMARGIN", new_y="NEXT")
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

        # Email metadata
        self.set_font("Helvetica", "B", 9)
        fields = [
            ("From", f"{email.get('sender_name', '')} <{email.get('sender_email', '')}>"),
            ("To", _format_recipients(email.get("recipients", ""))),
            ("Date", str(email.get("date_received", ""))[:19]),
            ("Subject", _safe(email.get("subject", ""))),
        ]

        if email.get("is_forwarded"):
            fields.append(("Originally From", email.get("original_sender", "")))
            fields.append(("Original Date", email.get("original_date", "")))

        for label, value in fields:
            if value:
                self.set_font("Helvetica", "B", 9)
                self.cell(20, 6, f"{label}:", new_x="END")
                self.set_font("Helvetica", "", 9)
                self.cell(0, 6, _safe(value)[:80], new_x="LMARGIN", new_y="NEXT")

        self.ln(5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

        # Email body
        body = email.get("body_text", "") or ""
        self.set_font("Helvetica", "", 9)
        self.multi_cell(0, 5, _safe(body))

        # Attachments list
        if attachments:
            self.ln(5)
            self.set_font("Helvetica", "B", 9)
            self.cell(0, 6, f"Attachments ({len(attachments)}):", new_x="LMARGIN", new_y="NEXT")
            self.set_font("Helvetica", "", 8)
            for att in attachments:
                fname = att.get("filename", "unknown")
                size = att.get("size_bytes", 0)
                size_str = f"{size / 1024:.0f} KB" if size > 0 else ""
                dup = " (duplicate)" if att.get("is_duplicate") else ""
                self.cell(0, 5, f"  - {fname} ({size_str}){dup}", new_x="LMARGIN", new_y="NEXT")

    def add_chat_exhibit(self, messages: list[dict], exhibit_label: str,
                         chat_name: str = ""):
        """Add a group of chat messages as an exhibit."""
        self._current_exhibit = exhibit_label
        self.add_page()

        self.set_font("Helvetica", "B", 14)
        self.set_text_color(0, 0, 0)
        self.cell(0, 10, f"{exhibit_label} — Chat: {chat_name}", new_x="LMARGIN", new_y="NEXT")
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

        self.set_font("Helvetica", "", 8)
        for msg in messages:
            ts = str(msg.get("timestamp", ""))[:16]
            sender = _safe(msg.get("sender", ""))
            text = _safe(msg.get("message_text", ""))

            if self.get_y() > 265:
                self.add_page()

            self.set_font("Helvetica", "B", 8)
            self.cell(0, 5, f"[{ts}] {sender}:", new_x="LMARGIN", new_y="NEXT")
            self.set_font("Helvetica", "", 8)
            self.multi_cell(0, 4, text)
            self.ln(2)


def build_timeline_pdf(db: Database, case_name: str = "", case_number: str = "",
                       date_start: str = "", date_end: str = "",
                       case_id: int = None) -> bytes:
    """Build a timeline PDF from all communications."""
    pdf = CasePulsePDF(case_name=case_name, case_number=case_number)

    # Cover page
    pdf.add_cover_page(
        title="Communication Timeline",
        subtitle=case_name,
        date_range=f"{date_start} to {date_end}",
    )

    # Get unified timeline
    items = db.get_unified_timeline(date_start=date_start, date_end=date_end, limit=50000)

    if not items:
        pdf.add_page()
        pdf.set_font("Helvetica", "", 12)
        pdf.cell(0, 10, "No communications found in the specified date range.")
        return pdf.output()

    # Get exhibit labels if case_id provided
    exhibit_map = {}
    if case_id:
        tags = db.get_evidence_tags_for_case(case_id)
        for t in tags:
            key = f"{t['item_type']}_{t['item_id']}"
            exhibit_map[key] = t.get("exhibit_label", "")

    # Timeline table
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 12, "Chronological Timeline", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    pdf.set_font("Helvetica", "B", 7)
    pdf.set_fill_color(230, 230, 230)
    col_widths = [22, 10, 35, 60, 20, 18, 25]
    headers = ["Date", "Type", "From", "Subject / Message", "Direction", "Flag", "Exhibit"]
    for w, h in zip(col_widths, headers):
        pdf.cell(w, 6, h, border=1, fill=True)
    pdf.ln()

    pdf.set_font("Helvetica", "", 6)
    current_date = ""
    for item in items:
        if pdf.get_y() > 265:
            pdf.add_page()
            pdf.set_font("Helvetica", "B", 7)
            pdf.set_fill_color(230, 230, 230)
            for w, h in zip(col_widths, headers):
                pdf.cell(w, 6, h, border=1, fill=True)
            pdf.ln()
            pdf.set_font("Helvetica", "", 6)

        dt = str(item.get("timestamp", ""))[:16]
        item_date = dt[:10]

        # Date separator
        if item_date != current_date:
            current_date = item_date
            pdf.set_font("Helvetica", "B", 7)
            pdf.set_fill_color(245, 245, 245)
            pdf.cell(sum(col_widths), 5, current_date, border=1, fill=True, new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 6)

        item_type = item.get("type", "email")[:5]
        sender = _safe(item.get("sender", ""))[:20]
        subject = _safe(item.get("subject", "") or item.get("body_preview", ""))[:35]
        direction = item.get("direction", "")[:5]
        fwd = "[FWD]" if item.get("is_forwarded") else ""
        exhibit_key = f"{item.get('type', 'email')}_{item.get('source_id', '')}"
        exhibit = exhibit_map.get(exhibit_key, "")[:12]

        pdf.cell(col_widths[0], 5, dt[11:16] if len(dt) > 11 else "", border=1)
        pdf.cell(col_widths[1], 5, item_type, border=1)
        pdf.cell(col_widths[2], 5, sender, border=1)
        pdf.cell(col_widths[3], 5, subject, border=1)
        pdf.cell(col_widths[4], 5, f"{direction} {fwd}".strip(), border=1)
        pdf.cell(col_widths[5], 5, "", border=1)  # Flag column
        pdf.cell(col_widths[6], 5, exhibit, border=1)
        pdf.ln()

    return pdf.output()


def build_exhibit_bundle_pdf(db: Database, case_id: int,
                              case_name: str = "", case_number: str = "",
                              exhibit_prefix: str = "",
                              include_notes: bool = False) -> bytes:
    """Build a complete exhibit bundle PDF with TOC and Bates numbering."""
    tags = db.get_evidence_tags_for_case(case_id)
    if not tags:
        pdf = CasePulsePDF(case_name=case_name, case_number=case_number)
        pdf.add_cover_page(title="Exhibit Bundle", subtitle="No exhibits tagged for this case")
        return pdf.output()

    # Sort by exhibit label
    tags.sort(key=lambda t: t.get("exhibit_label", "zzz"))

    pdf = CasePulsePDF(
        case_name=case_name,
        case_number=case_number,
        exhibit_prefix=exhibit_prefix,
    )

    # Cover page
    pdf.add_cover_page(
        title="Exhibit Bundle",
        subtitle=case_name,
    )

    # Build TOC items and exhibit data
    toc_items = []
    exhibits = []
    page_counter = 3  # cover + TOC start at page 3

    for tag in tags:
        exhibit_label = tag.get("exhibit_label", "")
        if not exhibit_label:
            continue

        item_type = tag["item_type"]
        item_id = tag["item_id"]

        if item_type == "email":
            email = db.get_email_by_id(item_id)
            if not email:
                continue
            attachments = db.get_attachments_for_email(item_id)
            toc_items.append({
                "exhibit_label": exhibit_label,
                "date": str(email.get("date_received", ""))[:10],
                "sender": email.get("sender_email", ""),
                "subject": email.get("subject", ""),
                "page": page_counter,
            })
            exhibits.append({
                "type": "email",
                "label": exhibit_label,
                "data": email,
                "attachments": attachments,
            })
            page_counter += 1  # Estimate

        elif item_type == "chat":
            import sqlite3 as _sql
            _chat_conn = _sql.connect(str(db.db_path))
            _chat_conn.row_factory = _sql.Row
            chat_msg = _chat_conn.execute(
                "SELECT * FROM chat_messages WHERE id = ?", (item_id,)
            ).fetchone()
            _chat_conn.close()

            chat_name = ""
            chat_msgs_data = []
            if chat_msg:
                chat_name = chat_msg["chat_name"] or ""
                # Get nearby messages for context (same chat, ±10 messages)
                _chat_conn2 = _sql.connect(str(db.db_path))
                _chat_conn2.row_factory = _sql.Row
                nearby = _chat_conn2.execute(
                    """SELECT * FROM chat_messages
                       WHERE chat_name = ? AND id BETWEEN ? AND ?
                       ORDER BY timestamp LIMIT 20""",
                    (chat_name, item_id - 10, item_id + 10)
                ).fetchall()
                _chat_conn2.close()
                chat_msgs_data = [dict(m) for m in nearby]

            toc_items.append({
                "exhibit_label": exhibit_label,
                "date": (chat_msg["timestamp"] or "")[:10] if chat_msg else "",
                "sender": chat_msg["sender"] if chat_msg else "Chat",
                "subject": chat_name,
                "page": page_counter,
            })
            exhibits.append({
                "type": "chat",
                "label": exhibit_label,
                "data": chat_msgs_data,
                "chat_name": chat_name,
            })
            page_counter += 1

    # Add TOC
    pdf.add_toc(toc_items)

    # Add exhibits
    for exhibit in exhibits:
        if exhibit["type"] == "email":
            pdf.add_email_exhibit(
                exhibit["data"],
                exhibit["label"],
                exhibit.get("attachments", []),
            )
        elif exhibit["type"] == "chat":
            pdf.add_chat_exhibit(
                exhibit["data"],
                exhibit["label"],
                chat_name=exhibit.get("chat_name", ""),
            )

    return pdf.output()


def _safe(text: str) -> str:
    """Make text safe for PDF rendering — handle Unicode gracefully."""
    if not text:
        return ""
    # Replace characters that fpdf2 can't render in default font
    # Keep common accented chars, replace emoji and CJK
    import unicodedata
    result = []
    for ch in text:
        try:
            ch.encode("latin-1")
            result.append(ch)
        except UnicodeEncodeError:
            # Try to decompose accented characters
            decomposed = unicodedata.normalize("NFD", ch)
            ascii_ch = decomposed.encode("ascii", errors="ignore").decode("ascii")
            result.append(ascii_ch if ascii_ch else "?")
    return "".join(result)


def _format_recipients(recipients) -> str:
    """Format recipients field for display."""
    if not recipients:
        return ""
    if isinstance(recipients, str):
        try:
            recipients = json.loads(recipients)
        except (json.JSONDecodeError, TypeError):
            return recipients
    if isinstance(recipients, list):
        parts = []
        for r in recipients:
            if isinstance(r, dict):
                parts.append(r.get("email", str(r)))
            else:
                parts.append(str(r))
        return ", ".join(parts)
    return str(recipients)
