"""Timeline export — Excel/CSV with exhibit references."""
from __future__ import annotations

import csv
import io
from datetime import datetime
from typing import Optional

from casepulse.storage.database import Database


def build_timeline_excel(db: Database, case_name: str = "",
                          date_start: str = "", date_end: str = "",
                          case_id: int = None) -> bytes:
    """Build a timeline Excel workbook."""
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side

    wb = Workbook()
    ws = wb.active
    ws.title = "Timeline"

    # Styles
    header_font = Font(bold=True, size=10)
    header_fill = PatternFill(start_color="D9E2F3", end_color="D9E2F3", fill_type="solid")
    date_sep_fill = PatternFill(start_color="F2F2F2", end_color="F2F2F2", fill_type="solid")
    thin_border = Border(
        left=Side(style="thin"), right=Side(style="thin"),
        top=Side(style="thin"), bottom=Side(style="thin"),
    )

    # Title rows
    ws.merge_cells("A1:H1")
    ws["A1"] = f"Communication Timeline — {case_name}"
    ws["A1"].font = Font(bold=True, size=14)
    ws["A2"] = f"Date Range: {date_start} to {date_end}"
    ws["A3"] = f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}"
    ws["A4"] = f"Generated by CasePulse"

    # Headers
    headers = ["Date", "Time", "Type", "From", "To", "Subject / Message",
               "Direction", "Forwarded", "Attachments", "Exhibit", "Flag", "Notes"]
    col_widths = [12, 8, 8, 30, 30, 50, 10, 10, 12, 15, 12, 40]

    for col_idx, (header, width) in enumerate(zip(headers, col_widths), 1):
        cell = ws.cell(row=6, column=col_idx, value=header)
        cell.font = header_font
        cell.fill = header_fill
        cell.border = thin_border
        cell.alignment = Alignment(horizontal="center")
        ws.column_dimensions[chr(64 + col_idx) if col_idx <= 26 else "A"].width = width

    # Set column widths properly for columns beyond Z
    for col_idx, width in enumerate(col_widths, 1):
        ws.column_dimensions[ws.cell(row=6, column=col_idx).column_letter].width = width

    # Get unified timeline
    items = db.get_unified_timeline(date_start=date_start, date_end=date_end, limit=50000)

    # Get exhibit labels if case_id provided
    exhibit_map = {}
    flag_map = {}
    if case_id:
        tags = db.get_evidence_tags_for_case(case_id)
        for t in tags:
            key = f"{t['item_type']}_{t['item_id']}"
            exhibit_map[key] = t.get("exhibit_label", "")
            flag_map[key] = t.get("flag", "")

    # Get annotations if case_id provided
    note_map = {}
    if case_id:
        all_notes = db.get_all_annotations_for_case(case_id)
        for n in all_notes:
            key = f"{n['item_type']}_{n['item_id']}"
            if key not in note_map:
                note_map[key] = []
            note_map[key].append(n["note_text"])

    # Data rows
    row = 7
    current_date = ""
    for item in items:
        ts = str(item.get("timestamp", ""))
        item_date = ts[:10]
        item_time = ts[11:16] if len(ts) > 11 else ""

        # Date separator row
        if item_date != current_date and item_date:
            current_date = item_date
            ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=len(headers))
            cell = ws.cell(row=row, column=1, value=current_date)
            cell.font = Font(bold=True, size=9)
            cell.fill = date_sep_fill
            row += 1

        item_type = item.get("type", "email")
        sender = item.get("sender", "")
        subject = item.get("subject", "") or item.get("body_preview", "")
        direction = item.get("direction", "")
        is_fwd = "Yes" if item.get("is_forwarded") else ""
        has_att = "Yes" if item.get("has_attachments") else ""
        exhibit_key = f"{item_type}_{item.get('source_id', '')}"
        exhibit = exhibit_map.get(exhibit_key, "")
        flag = flag_map.get(exhibit_key, "")
        notes = " | ".join(note_map.get(exhibit_key, []))

        # Recipients (for emails)
        to_field = ""
        if item_type == "email" and item.get("source_id"):
            email_data = db.get_email_by_id(item["source_id"])
            if email_data:
                recips = email_data.get("recipients", "")
                if recips:
                    import json
                    try:
                        rlist = json.loads(recips) if isinstance(recips, str) else recips
                        to_field = ", ".join(
                            r.get("email", str(r)) if isinstance(r, dict) else str(r)
                            for r in rlist
                        )
                    except Exception:
                        to_field = str(recips)

        values = [item_date, item_time, item_type, sender, to_field,
                  subject[:200], direction, is_fwd, has_att, exhibit, flag, notes]

        for col_idx, val in enumerate(values, 1):
            cell = ws.cell(row=row, column=col_idx, value=val)
            cell.border = thin_border
            cell.alignment = Alignment(vertical="top", wrap_text=col_idx in (6, 12))
            cell.font = Font(size=9)

        row += 1

    # Summary sheet
    ws2 = wb.create_sheet("Summary")
    ws2["A1"] = "Timeline Summary"
    ws2["A1"].font = Font(bold=True, size=14)
    ws2["A3"] = f"Case: {case_name}"
    ws2["A4"] = f"Date Range: {date_start} to {date_end}"
    ws2["A5"] = f"Total Items: {len(items)}"
    ws2["A6"] = f"Emails: {sum(1 for i in items if i['type'] == 'email')}"
    ws2["A7"] = f"Chat Messages: {sum(1 for i in items if i['type'] == 'chat')}"
    ws2["A8"] = f"With Attachments: {sum(1 for i in items if i.get('has_attachments'))}"
    ws2["A9"] = f"Forwarded: {sum(1 for i in items if i.get('is_forwarded'))}"
    ws2["A10"] = f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}"

    # Save to bytes
    output = io.BytesIO()
    wb.save(output)
    return output.getvalue()


def build_timeline_csv(db: Database, date_start: str = "", date_end: str = "",
                       case_id: int = None) -> str:
    """Build a timeline CSV string."""
    items = db.get_unified_timeline(date_start=date_start, date_end=date_end, limit=50000)

    exhibit_map = {}
    flag_map = {}
    if case_id:
        tags = db.get_evidence_tags_for_case(case_id)
        for t in tags:
            key = f"{t['item_type']}_{t['item_id']}"
            exhibit_map[key] = t.get("exhibit_label", "")
            flag_map[key] = t.get("flag", "")

    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(["Date", "Time", "Type", "From", "Subject/Message",
                     "Direction", "Forwarded", "Attachments", "Exhibit", "Flag"])

    for item in items:
        ts = str(item.get("timestamp", ""))
        exhibit_key = f"{item.get('type', 'email')}_{item.get('source_id', '')}"
        writer.writerow([
            ts[:10],
            ts[11:16] if len(ts) > 11 else "",
            item.get("type", ""),
            item.get("sender", ""),
            (item.get("subject", "") or item.get("body_preview", ""))[:200],
            item.get("direction", ""),
            "Yes" if item.get("is_forwarded") else "",
            "Yes" if item.get("has_attachments") else "",
            exhibit_map.get(exhibit_key, ""),
            flag_map.get(exhibit_key, ""),
        ])

    return output.getvalue()
